Jaded-Encoding-Thaumaturgy/vs-preview

- vspreview/init.py
pretty-traceback was removed from deps in 7ddc99f9ea001ab3c2d6d39e26bc1d366ad83c6f
I'm assuming the intention was to remove it from production path all-together.
> Remove pretty_traceback references.

- vspreview/toolbars/pipette/toolbar.py
The last code cleanup (da1bfe6456f01d8473fe7b0c3f978f65b7a7c3e3) resulted in referencing `cache[0]` before it was populated.
> Fix pipette hover crash on fresh pipette frame cache.

- vspreview/main/window.py
I'm not certain exactly what triggered this scenario, but the situation that occurred is that `self.current_output` is an attribute on the class that `self` is, and that attribute is set to `None`. `hasattr` returns `True` because there is an attribute on `self` called `current_output`, even though it is `None`.
> Fix a crash that occurs when opening a second file within a workspace

- .vscode/settings.json
- vspreview/core/abstracts.py
- vspreview/init.py
- vspreview/main/window.py
I had a use case for this as part of a script to find the frame with the most out-of-range pixels in a video, and then display it. My hope is that it might be useful to someone else as well.
> Add --frame CLI arg for seeking to a specified frame on load

- vspreview/core/abstracts.py
Crash was due to sub-layouts being included in the layout's items being iterated and sub-layouts don't contain a singular widget. Sub-layouts are now removed, cleared, and deleted. Widgets removed from the layout are deleted as before.
`widget.deleteLater()` will remove the parent relationship automatically so `widget.setParent(None)` is unnecessary.
Fixes Irrational-Encoding-Wizardry/vs-preview#63
> Fix crash when Frame Props dialog is cleared during output switching.

- vspreview/main/timeline.py
- vspreview/toolbars/scening/dialog.py
- vspreview/toolbars/scening/toolbar.py
This fixes the following crash scenarios:
- Hovering cursor on timeline scene notch.
- Browsing to new frames while there are listed scenes.
- Editing scene properties in the scene list dialog despite no scene selected.
It also fixes the scene label not being added for single-frame scenes. Some of these issues were caused by the PyQt6 refactor, but a couple were present beforehand.
Fixes Irrational-Encoding-Wizardry/vs-preview#62.
> Fix recent Scening toolbar and workflow issues

- vspreview/toolbars/comp/toolbar.py
This patch adds a missing `elif` condition for the P-frame checkbox. Previously with only P-frames checked, unchecking it would result in the B-frame checkbox being forced-checked.
> Fix force-checking the P-frame checkbox

- vspreview/core/abstracts.py
- vspreview/main/timeline.py
- vspreview/plugins/__init__.py
- vspreview/plugins/abstract.py
- vspreview/toolbars/scening/toolbar.py
Example:
```
from __future__ import annotations
from PyQt6.QtWidgets import QTableView
from ..core import Frame
from .abstract import AbstractPlugin
from PyQt6.QtGui import QColor
from PyQt6.QtCore import Qt
from typing import cast
from ..core import Notches,VBoxLayout, PushButton
__all__ = [
'Plugin'
]
class Plugin(AbstractPlugin, QTableView):
_plugin_name = 'Test notches'
__slots__ = (
)
def on_current_frame_changed(self, frame: Frame) -> None:
pass
def get_notches(self) -> Notches:
marks = Notches()
marks.add(Frame(15), cast(QColor, Qt.GlobalColor.darkCyan))
marks.add(Frame(30), cast(QColor, Qt.GlobalColor.darkCyan))
return marks
def is_notches_visible(self) -> bool:
return self.isVisible()
def setup_ui(self) -> None:
VBoxLayout(self, [
PushButton("Hello"),
])
```
> Make plugins able to have notches

- vspreview/toolbars/comp/toolbar.py
previous logic may result in cache becoming stuck on error. we can re-try until the api request succeeds.
> fix cache logic

- requirements.txt
Fixes tooltip styling.
Before:
After:
> Update PyQt6 to v6.6.1

- vspreview/toolbars/comp/toolbar.py
It was checking against the string so if the list contained 1200 and you tried adding 12, 20, 200, 120, 1, 2 or 0 it would fail.
> Fix issue with remove

- vspreview/plugins/builtins/frame_props.ppy
2818451 updated the plugin to use a single `TableModel` instance, but changes to the underlying data are not emitted as signals, so the view doesn't update when the data changes. This patch fixes the issue by emitting the `layoutChanged` signal to trigger a redisplay.
Didn't use `dataChanged` because it's possible that there are more or less rows (props) in the new table data, hence a layout change. Also didn't implement this in `TableModel` since the data mutation is happening directly in the plugin.
> Fix frames props view not updating on frame change

- vspreview/toolbars/scening/toolbar.py
OGM chapters don't need to have strictly two digits for hours/minutes/seconds. Currently, copying vs-preview's own timestamps into the chapter file will result in them being skipped.
This matches MKVToolNix's behavior:
https://gitlab.com/mbunkus/mkvtoolnix/-/blob/18bd87e/src/common/chapters/chapters.cpp#L59
Also, fixed a typo in the docstring.
> Allow arbitrary number of digits in OGM chapter times

- vspreview/plugins/builtins/slowpics_comp/main.py
Some keys can be a 32 char string, this supports them.
> Support alternate api-keys in tmdb

- vspreview/plugins/builtins/slowpics_comp/main.py
Some idiot Italian removed this code. Hope he burns his pasta.
> Fix slow.pics again

- vspreview/plugins/builtins/frame_props.ppy
- vspreview/plugins/builtins/frame_props/category.py
- vspreview/plugins/builtins/frame_props/exclude.py
- vspreview/plugins/builtins/frame_props/lut.py
This PR adds the following:
- Categorisation (see [here](##categories-and-props))
- Dynamically add tables if any props of the corresponding category are found
- Add some special handling for props from common plugins/JET functions
- Separate all the LUTs and the like to their own files for easier modifying and a better oversight
- "Prettified" is default now. Switch instead asks if the user wants to see the raw data 
- more in line with what was asked in #173
- General refactoring
- Prop sorting (reserved props always up top)
- Double-click to copy the value of the selected row
- Strips prop keys/values in the prettify window
- Handle lambdas in prop prettifier function for more specialised outputs
Screenshots:
The following categories were added, and these props get sorted into them …
> Overhaul frame props plugin

- vspreview/main/settings.py
Updates the following label(s):
- PNG compression
- Clarifies what the max value is
Changes the following values:
- Zoom levels
- Use more sane zoom levels, doubling rather having semi-random values (50, 100, 200, 400, 800, etc.).
Users who want those weird zooms can still set them themselves.
- Plugin panel position save
- Default to "Local" (from: "No").
> Update default settings values

- vspreview/main/window.py
This is better for the same reason as why %appdata%/.vspreview was moved to %appdata%/vspreview.
> Rename global storage file to global.yml from .global.yml

- vspreview/core/abstracts.py
- vspreview/core/bases.py
- vspreview/core/types/misc.py
- vspreview/core/types/units.py
- vspreview/core/types/video.py
- vspreview/main/window.py
- vspreview/plugins/abstract.py
See the individual commit messages for more information.
> Make YAML storage loading safer and able to catch errors

- vspreview/plugins/builtins/slowpics_comp/main.py
- vspreview/plugins/builtins/slowpics_comp/workers.py
- Prevents crash if no frames were extracted.
- Don't start upload if it was stopped.
> Fix Crashing issues

- vspreview/plugins/builtins/slowpics_comp/workers.py
On ffms2 this match fails, I assume due to different encoding types. So we force it to be the same to fix it.
> Fix PictType issue

- vspreview/plugins/builtins/slowpics_comp/main.py
- vspreview/plugins/builtins/slowpics_comp/settings.py
- vspreview/plugins/builtins/slowpics_comp/utils.py
- vspreview/plugins/builtins/slowpics_comp/workers.py
You no longer need to get cookies from your browser. I will now create its own session by using the user provided credentials. It only stores the cookies, so no password or usernames are stored on disk.
> Rewrite slow.pics session handling

- vspreview/plugins/builtins/split_view.ppy
Sometimes, there are artifacts in UV planes that you want to fix but are hard to spot due to the nature of the pixel distribution on these planes.
Offsetting the planes toward the minimum value can help to see more details.
This PR adds the possibility to offset the UV planes:
- by a fixed value
- by the minimum value of each frame (AKA `PlaneStatsMin`) toward lowest value
- by the maximum value of each frame (AKA `PlaneStatsMax`) toward peak value
> Allow offsetting of UV planes in SplitPlanesPlugin

- vspreview/core/custom/dragnavigator.py
repaint() directly invokes paintEvent and doesn't combine multiple paint requests. update() allows Qt to optimize update requests.
Fixes: #198
> Coalesce paintEvent callbacks in dragnavigator

- docs/installation/install_vim.rst
In the previously suggested installation with vim/neovim, you had the editor frozen until vs-preview was quit, with no possibility of modifying the script in the editor and reloading it vs-preview. This PR adds information on how to use the jobcontrol feature in vim/neovim to start vs-preview asynchronously.
> Add doc on how to start vs-preview asynchronously in vim/neovim

- vspreview/toolbars/benchmark/settings.py
- vspreview/toolbars/benchmark/toolbar.py
Example
```csv
Date & Time,Node,Index,Start,End,Frames Processed,Average FPS,Total Time (s),Thread Count,Prefetch,Unsequenced
2025-06-12 16:23:45,JP BD,0,0,999,530,429.62778021864005,1.233626,16,True,True
2025-06-12 16:25:42,JP BD,0,0,999,371,371.3490681240366,0.99906,16,True,True
```
Saves file whenever `run` is done or cancelled.
Sends a message when done saving to help users find the file:
> Benchmark: Store log results to CSV

- vspreview/main/window.py
Removing the second call to `clear_monkey_runpy` appears to fix #232. I'm not entirely sure what the side effects might be. I left the `try/except` statements in place in case `load_script` can throw an error (if that's even possible).
> Remove clear_monkey_runpy when script is loading successfully
