Jaded-Encoding-Thaumaturgy/vs-preview

- vspreview/toolbars/scening/toolbar.py
Originally added here: https://github.com/AkarinVS/vapoursynth-preview/pull/9
> Add rfs style import

- vspreview/toolbars/comp/settings.py
- vspreview/toolbars/comp/toolbar.py
- Login Support
- Tag Support
- Delete After Support
- TMDB support
> Fully support slow.pics uploading

- vspreview/toolbars/comp/toolbar.py
- vspreview/toolbars/misc/toolbar.py
> Add current frame to the manual frames hotkey

- vspreview/toolbars/comp/toolbar.py
Will revert back to his default
> Go back to default after Slowbro said to.

- vspreview/toolbars/comp/toolbar.py
- Fix tags not loading
- Add support for new tags
> Fix tags system

- vspreview/toolbars/comp/toolbar.py
This will fully support slow.pics tag system. If the tag is missing from slow.pics it will be made so it can be used.
> Support fully Slow.pics tags

- vspreview/toolbars/comp/toolbar.py
> Check session before extracting images

- vspreview/core/bases.py
For some reason which I do not pretend to understand, assigning to `cls.instance` in `Singleton.__new__` crashes on Python 3.12 when the class also inherits from QObject or something of the sort. This is very likely a bug in PyQt6 but for now we can just replace `cls.instance` with a list and append to it so no assignment happens in `__new__`.
> Work around silent crash on Python 3.12

- vspreview/api/other.py
> install_vscode_launch: Change type to debugpy

- vspreview/plugins/split_view.ppy
Fixes: https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/issues/143
> Fix split view crash on float YUV

- vspreview/toolbars/comp/settings.py
- vspreview/toolbars/comp/toolbar.py
Added this so you don't need to use frameinfo so encoders can do rescaling from the comp.
Example comp https://slow.pics/c/bAumeRev (9 day expiry)
> Add frame type to image title

- vspreview/core/types/video.py
- vspreview/toolbars/comp/toolbar.py
It will use fpng if it is found in vs.core otherwise it will use the old slow option.
Also fixes a few other issues I noticed while testing.
> Support fpng for image export

- vspreview/toolbars/comp/toolbar.py
Will select frames in blocks. Say a video has 100 frames and we want 10 random frames. It will select frames from 0-9 then 10-19 and so on.
> Random Frame Distribution

- vspreview/toolbars/comp/settings.py
- vspreview/toolbars/comp/toolbar.py
Prevents session expiring, always logs in at the start of the flow.
> Support login instead of session

- vspreview/toolbars/comp/toolbar.py
- Fix single comp uploads
- Fix tag system request
- Add headers to requests
> Fix issues with slow.pics

- vspreview/core/types/video.py
- vspreview/toolbars/playback/settings.py
> Add chroma kernel selector

- vspreview/plugins/builtins/slowpics_comp/main.py
- vspreview/plugins/builtins/slowpics_comp/utils.py
- vspreview/plugins/builtins/slowpics_comp/workers.py
Values are from Reza, might need adjusting?
> Support dark and light frames generation

- vspreview/toolbars/playback/settings.py
- vspreview/toolbars/scening/settings.py
- vspreview/toolbars/scening/toolbar.py
> fix playback & scening settings not applied

- vspreview/__init__.py
As described by https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/issues/190
> Work around PyQt loading outdated MSVC runtime

- vspreview/api/output.py
* Add possibility to set an index number to an output
* Accepts Iterable of nodes
* Fix #181
* Is backward compatible but untyped
> Extend functionality of set_output

- vspreview/core/vsenv.py
Required by https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/pull/28
> Remove usage of _finalize_core

- requirements.txt
- vspreview/core/types/video.py
- vspreview/main/window.py
- vspreview/toolbars/playback/toolbar.py
Related to:
- https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/commit/167adeb4daed83de32b029b821b982a8a39dee2c 
- https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/commit/be297f14c6e380b3486ec152b6b111b6ae9a8807
- https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/commit/e5ff9d35b8cc33d5eed413519201095b847130b1 
- https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/commit/02bfb9df5843f13f43c53dd162e1e9991df66d8f
Original issue was: https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/pull/176
> Fix timecodes handling
